### ISSUE TITLE
优化建议 网络过载

### ISSUE THREAD

**Issue by 347180440** [GZY-mingbai/ScreenInMC-Plugin#10]
我发现屏幕发包是给全服玩家 而不是屏幕半径内的玩家
不管我在服务器哪一个位置 都吃我5-7M 当我删掉屏幕后仅占用0.3M
我尝试在spigot.yml中
把杂项显示距离选项【包括展示框】 中的misc 改为10 普通的展示框只能在玩家半径内显示 但ScreenInMC 直接无视了这个选项 不管玩家 离屏幕多远 还是会显示 并发包给玩家
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      display: 128
      other: 64

**Comment by GZY-mingbai** [comment]
在提交(99b2921) 中，我添加了距离限制，在config.yml中可以进行修改，只需从GitHub Releases或蓝奏云重新下载即可
