### ISSUE TITLE
输入网页URL时回弹，加载网页时造成服务器严重卡顿

### ISSUE THREAD

**Issue by Neko110923** [GZY-mingbai/ScreenInMC-Plugin#17]
ScreenInMC服务器:
1.12.2 SpigotMC

链接地址:BungeeCord+127.0.0.1
(ViaVersion+ViaBackWards+ViaRewind，玩家我的世界版本1.8.9)
进入服务器后过了一会儿直接被BC踢到主大厅，原因是该服务器没有任何的回应(The server you were previously on went down, you have been connected to a fallback server)

**Comment by Neko110923** [comment]
补充:卡顿不是TPS降低，在控制台中执行命令反应正常，但玩家在游戏里执行命令则卡的要死

**Comment by GZY-mingbai** [comment]
屏幕过大，地图占用过多网络资源，可以尝试设置帧率限制(在编辑器中)，或减小屏幕大小

**Comment by Neko110923** [comment]
缩小屏幕后恢复正常
