### ISSUE TITLE
输入/screen installChromium没反应

### ISSUE THREAD

**Issue by kejio5** [GZY-mingbai/ScreenInMC-Plugin#18]
两个端都试过了，分别是arm v8a 还有没有amd64的架构都是linux
![Uploading Screenshot_2023-08-27-23-39-09-48_a252b927494330cdc2c8ba3b3f952e5e.png…]()
![Uploading Screenshot_2023-08-27-23-38-42-50_84d3000e3f4017145260f7618db1d683.png…]()

**Comment by GZY-mingbai** [comment]
GitHub readme 还没有更新，安装 Chromium现在改为在网页浏览器核心中

放置一块屏幕，切换核心为网页浏览器，然后就可以看到安装Chromium 按钮
