### ISSUE TITLE
我是1.19版本用的Bukkit服务端服务器端,问题是客户端内输入命令无效比如输入/screen help,输出 /screen <args>,其它命令同样只输出/screen <args>

### ISSUE THREAD

**Issue by huangyihao2013** [GZY-mingbai/ScreenInMC-Plugin#30]
我是1.19版本用的Bukkit服务端服务器端,问题是客户端内输入命令无效比如输入/screen help,输出 /screen <args>,其它命令同样只输出/screen <args>

**Comment by GZY-mingbai** [comment]
提供一下服务器日志

**Comment by huangyihao2013** [comment]
> 提供一下服务器日志

[Uploading latest.log…]()

**Comment by huangyihao2013** [comment]
> 试一试这个 https://github.com/GZY-mingbai/ScreenInMC-Plugin/actions/runs/8019173646/artifacts/1269621943
解决了，谢谢

**Comment by GZY-mingbai** [comment]
如果你使用的是VMware VNC 
那么这貌似是Vernacular VNC库的问题
具体见https://github.com/shinyhut/vernacular-vnc/issues/22
这个问题已经修复，但还没发布Release

目前你可以尝试在虚拟机中安装VNC服务器来解决这个问题
