### ISSUE TITLE
看不了B站

### ISSUE THREAD

**Issue by 347180440** [GZY-mingbai/ScreenInMC-Plugin#7]
屏幕显示【你当前的浏览器不正常 HTML5播放器
】

**Comment by GZY-mingbai** [comment]
默认的 Chromium 是从 https://github.com/jcefmaven/jcefbuild 仓库下载的，并不支持 HTML5 视频播放器

我在https://b23.tv/MmBxCJ1 视频置顶评论的回复中，提供了一个支持HTML5视频播放的Chromium(需要64 位 Windows)，可自行安装，安装方法在压缩包中
